--- #YAML:1.0
name:               Astro-SkyX
version:            0.04
abstract:           Perl extension for communications with The SkyX Scripting Engine Version 10.2.0 (Build 6519 and later).
author:
    - Robert Woodard <kayak.man@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:    1.31
    Scalar::Util:  1.22
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
